
export interface MovieResponse {
    page:          number;
    results:       Movie[];
    total_pages:   number;
    total_results: number;
}
export interface MovieDetails {
    created_by:     string;
    description:    string;
    favorite_count: number;
    id:             string;
    results:        Movie[];
    item_count:     number;
    iso_639_1:      ISO639_1;
    name:           string;
    poster_path:    string;
}

export enum ISO639_1 {
    En = "en",
}

export interface Movie {
    adult:             boolean;
    backdrop_path:     string;
    id:                number;
    title:             string;
    original_language: string;
    original_title:    string;
    overview:          string;
    poster_path:       string;
    media_type:        string;
    genre_ids:         number[];
    popularity:        number;
    release_date:      string;
    video:             boolean;
    vote_average:      number;
    vote_count:        number;
    actors:            string;
   
}

// Generated by https://quicktype.io

